name: Generate Transcript and Upload

on:
  workflow_dispatch:    # manual trigger
  push:                 # triggers on every push
    branches:
      - main           # or any branch you want
jobs:
  generate_transcript:
    name: Generate Transcript (Python 3.12)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gpt4all

    # - name: Download GPT4All model
    #   run: |
    #     mkdir -p models
    #     wget -O models/Meta-Llama-3-8B-Instruct.Q4_0.gguf https://gpt4all.io/models/Meta-Llama-3-8B-Instruct.Q4_0.gguf

    - name: Generate transcripts
      run: python generate_transcript.py



  upload_mega:
    name: Upload to MEGA (Python 3.10)
    runs-on: ubuntu-latest
    needs: generate_transcript  # waits for transcript generation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install mega.py
      run: |
        pip install mega.py


    - name: Upload output.json to MEGA
      run: |
        python mega_upload.py
      env:
        M_TOKEN: ${{ secrets.M_TOKEN }}
