name: Generate Transcript and Upload

on:
  workflow_dispatch:    # manual trigger
  push:                 # triggers on every push
    branches:
      - main           # or any branch you want
jobs:
  generate_transcript:
    name: Generate Transcript (Python 3.12)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gpt4all gdown telebot


    - name: Generate transcripts
      run: python generate_transcript.py
      env:
        C_ID: ${{ secrets.CHAT_ID }}
        TOKEN: ${{ secrets.TOKEN }}
